import archiver from 'archiver'
import { createHash } from 'node:crypto'
import { PassThrough } from 'node:stream'
import PDFDocument from 'pdfkit'
import {
  exportToCSV,
  exportToJSON,
  generateSummaryReport,
} from './rfd01Generator.js'
import type {
  ApprovedMatch,
  Statement3B,
  SummaryReport,
} from '../types/index.js'

const GST_PORTAL_URL = 'https://www.gst.gov.in/'

function safePart(s: string, max = 48): string {
  return s
    .trim()
    .replace(/[^\w.-]+/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_|_$/g, '')
    .slice(0, max) || 'NA'
}

function periodSlug(summary: SummaryReport): string {
  const a =
    safePart(summary.periodFrom.replace(/\//g, ''), 12) || 'NA'
  const b = safePart(summary.periodTo.replace(/\//g, ''), 12) || 'NA'
  return `${a}_to_${b}`
}

function bundleDateStamp(): string {
  return new Date().toISOString().slice(0, 10).replace(/-/g, '')
}

export function getBundleZipBaseName(
  gstin: string,
  summary: SummaryReport,
): string {
  const g = safePart(gstin, 20) || 'UNKNOWN'
  return `GST_Refund_Bundle_${g}_${periodSlug(summary)}_${bundleDateStamp()}`
}

function csvEscape(value: string): string {
  if (/[",\r\n]/.test(value)) {
    return `"${value.replace(/"/g, '""')}"`
  }
  return value
}

export function generateCAReadme(summary: SummaryReport): string {
  return `GST RFD-01 refund bundle — instructions for chartered accountant
Generated for GSTIN: ${summary.exporterGstin}
Period covered (invoice dates): ${summary.periodFrom} to ${summary.periodTo}
Transactions in bundle: ${summary.transactionCount}

Estimated eligible refund (placeholder 18% of taxable, INR): ${summary.totalEligibleRefundEstimateInr.toFixed(2)}
Total taxable value (INR): ${summary.totalTaxableValueInr.toFixed(2)}

HOW TO USE THIS BUNDLE
-----------------------
1) Log in to the official GST portal: ${GST_PORTAL_URL}
2) Go to: Services → Refunds → Application for Refund (or Refunds dashboard per current menu labels).
3) Select the category for refund of unutilised ITC on account of exports without payment of tax (LUT / bond), as applicable to your client.
4) Upload the Statement 3B CSV from folder 01_Statement_3B (RFD01_Statement3B_*.csv) using the GST offline utility / portal import flow as required for RFD-01.
5) Attach the FIRA / BRC documents from folder 02_FIRA_Documents and invoice copies from folder 03_Invoice_Copies as supporting evidence.
6) Review 04_Match_Report/Match_Audit_Trail.csv for how each FIRA was paired to an invoice.
7) Use 05_Summary/Refund_Summary.pdf as a human-readable overview; verify figures against your working papers.

IMPORTANT
---------
- This ZIP is generated by Skydo GST ITC refund tooling; you must independently verify all figures and statutory eligibility before filing.
- CHECKSUM.txt lists MD5 digests of bundled files (excluding the checksum file itself) for integrity checks.
- Do not share GST portal credentials by email; use secure channels agreed with your client.

LUT reference(s) noted in data: ${summary.lutNumbersUsed.length ? summary.lutNumbersUsed.join(', ') : '—'}
`
}

function auditDefaults(m: ApprovedMatch): {
  method: string
  confidence: string
  approvedBy: string
  approvedAt: string
} {
  const now = new Date().toISOString()
  return {
    method: m.matchMethod ?? 'Manual',
    confidence: m.matchConfidence ?? '—',
    approvedBy: m.approvedBy ?? 'Exporter / system',
    approvedAt: m.approvedAt ?? now,
  }
}

export function generateMatchAuditTrail(matches: ApprovedMatch[]): string {
  const headers = [
    'FIRA Ref',
    'Invoice No',
    'Match Method',
    'Confidence',
    'Approved By',
    'Timestamp',
  ]
  const lines = [headers.join(',')]
  for (const m of matches) {
    const a = auditDefaults(m)
    lines.push(
      [
        csvEscape(m.fira.referenceNo),
        csvEscape(m.invoice.invoiceNo),
        csvEscape(a.method),
        csvEscape(a.confidence),
        csvEscape(a.approvedBy),
        csvEscape(a.approvedAt),
      ].join(','),
    )
  }
  return lines.join('\r\n')
}

export function generateChecksum(files: Map<string, Buffer>): string {
  const paths = [...files.keys()].sort()
  const lines: string[] = []
  for (const p of paths) {
    const buf = files.get(p)
    if (!buf) continue
    const hash = createHash('md5').update(buf).digest('hex')
    lines.push(`${p}  ${hash}`)
  }
  return lines.join('\r\n')
}

function firaIndexCsv(
  matches: ApprovedMatch[],
  internalPaths: string[],
): string {
  const h = ['Reference', 'AmountInr', 'ValueDate', 'SourceFile', 'PathInZip']
  const lines = [h.join(',')]
  matches.forEach((m, i) => {
    lines.push(
      [
        csvEscape(m.fira.referenceNo),
        String(m.fira.amountInr),
        csvEscape(m.fira.valueDate),
        csvEscape(m.fira.sourceFileName),
        csvEscape(internalPaths[i] ?? ''),
      ].join(','),
    )
  })
  return lines.join('\r\n')
}

function invoiceIndexCsv(
  matches: ApprovedMatch[],
  internalPaths: string[],
): string {
  const h = [
    'InvoiceNo',
    'Client',
    'InvoiceValueInr',
    'InvoiceDate',
    'SourceFile',
    'PathInZip',
  ]
  const lines = [h.join(',')]
  matches.forEach((m, i) => {
    lines.push(
      [
        csvEscape(m.invoice.invoiceNo),
        csvEscape(m.invoice.clientNameRaw),
        String(m.invoice.invoiceValue),
        csvEscape(m.invoice.invoiceDate),
        csvEscape(m.invoice.sourceFileName),
        csvEscape(internalPaths[i] ?? ''),
      ].join(','),
    )
  })
  return lines.join('\r\n')
}

function pdfBufferFromDoc(
  build: (doc: InstanceType<typeof PDFDocument>) => void,
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 })
    const chunks: Buffer[] = []
    doc.on('data', (c: Buffer) => chunks.push(c))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)
    build(doc)
    doc.end()
  })
}

export async function refundSummaryPdfBuffer(
  summary: SummaryReport,
): Promise<Buffer> {
  return pdfBufferFromDoc((doc) => {
    doc.fontSize(16).text('RFD-01 — Refund summary (CA)', { underline: true })
    doc.moveDown()
    doc.fontSize(10)
    doc.text(`Exporter GSTIN: ${summary.exporterGstin}`)
    doc.text(`Period: ${summary.periodFrom} to ${summary.periodTo}`)
    doc.text(`Transactions: ${summary.transactionCount}`)
    doc.text(`Total taxable value (INR): ${summary.totalTaxableValueInr.toFixed(2)}`)
    doc.text(
      `Estimated eligible refund (18% proxy, INR): ${summary.totalEligibleRefundEstimateInr.toFixed(2)}`,
    )
    doc.moveDown()
    doc.fontSize(8).fillColor('#444444')
    doc.text(
      'Figures are generated for review; verify against books and GSTR data before filing.',
      { width: 480 },
    )
  })
}

async function placeholderPdf(title: string, detail: string): Promise<Buffer> {
  return pdfBufferFromDoc((doc) => {
    doc.fontSize(12).text(title, { underline: true })
    doc.moveDown()
    doc.fontSize(10).text(detail)
    doc.moveDown()
    doc
      .fontSize(9)
      .fillColor('#666666')
      .text(
        'Replace this placeholder with the original PDF from your records if this file was not supplied by the exporter.',
        { width: 460 },
      )
  })
}

async function padBuffers(
  incoming: Buffer[],
  count: number,
  label: string,
): Promise<Buffer[]> {
  const out: Buffer[] = [...incoming]
  while (out.length < count) {
    const i = out.length
    const b = await placeholderPdf(
      `${label} ${i + 1}`,
      'No binary was uploaded for this row; this PDF is a structural placeholder for the CA bundle.',
    )
    out.push(b)
  }
  return out.slice(0, count)
}

/**
 * Builds all inner ZIP entries (no CHECKSUM.txt yet).
 */
async function buildFileMap(
  statement: Statement3B,
  approvedMatches: ApprovedMatch[],
  firaDocuments: Buffer[],
  invoiceDocuments: Buffer[],
): Promise<Map<string, Buffer>> {
  const files = new Map<string, Buffer>()
  const summary = generateSummaryReport(statement)
  const gstin = safePart(summary.exporterGstin, 20)
  const period = periodSlug(summary)

  const stmtPrefix = `01_Statement_3B/RFD01_Statement3B_${gstin}_${period}`
  files.set(`${stmtPrefix}.csv`, Buffer.from(exportToCSV(statement), 'utf8'))
  files.set(
    `${stmtPrefix}.json`,
    Buffer.from(JSON.stringify(exportToJSON(statement), null, 2), 'utf8'),
  )

  const n = approvedMatches.length
  const firaBufs = await padBuffers(firaDocuments, n, 'FIRA')
  const invBufs = await padBuffers(invoiceDocuments, n, 'Invoice')

  const firaPaths: string[] = []
  const invPaths: string[] = []

  approvedMatches.forEach((m, i) => {
    const utr = safePart(m.fira.referenceNo, 24)
    const amt = Math.round(m.fira.amountInr)
    const d = safePart(m.fira.valueDate.replace(/-/g, ''), 12)
    const fName = `02_FIRA_Documents/FIRA_${utr}_${amt}_${d}.pdf`
    firaPaths.push(fName)
    files.set(fName, firaBufs[i]!)

    const invNo = safePart(m.invoice.invoiceNo, 20)
    const client = safePart(m.invoice.clientNameRaw, 16)
    const invAmt = Math.round(m.invoice.invoiceValue)
    const iName = `03_Invoice_Copies/INV_${invNo}_${client}_${invAmt}.pdf`
    invPaths.push(iName)
    files.set(iName, invBufs[i]!)
  })

  files.set(
    '02_FIRA_Documents/FIRA_Index.csv',
    Buffer.from(firaIndexCsv(approvedMatches, firaPaths), 'utf8'),
  )
  files.set(
    '03_Invoice_Copies/Invoice_Index.csv',
    Buffer.from(invoiceIndexCsv(approvedMatches, invPaths), 'utf8'),
  )

  files.set(
    '04_Match_Report/Match_Audit_Trail.csv',
    Buffer.from(generateMatchAuditTrail(approvedMatches), 'utf8'),
  )

  files.set(
    '05_Summary/README_FOR_CA.txt',
    Buffer.from(generateCAReadme(summary), 'utf8'),
  )
  files.set(
    '05_Summary/Refund_Summary.pdf',
    await refundSummaryPdfBuffer(summary),
  )

  return files
}

export async function assembleCABundle(
  statement: Statement3B,
  approvedMatches: ApprovedMatch[],
  firaDocuments: Buffer[],
  invoiceDocuments: Buffer[],
): Promise<Buffer> {
  const content = await buildFileMap(
    statement,
    approvedMatches,
    firaDocuments,
    invoiceDocuments,
  )
  const checksumText = generateChecksum(content)
  content.set('CHECKSUM.txt', Buffer.from(checksumText, 'utf8'))

  return new Promise((resolve, reject) => {
    const archive = archiver('zip', { zlib: { level: 9 } })
    const passthrough = new PassThrough()
    const chunks: Buffer[] = []

    passthrough.on('data', (c: Buffer) => chunks.push(c))
    passthrough.on('end', () => resolve(Buffer.concat(chunks)))
    passthrough.on('error', reject)

    archive.on('error', reject)
    archive.pipe(passthrough)

    const ordered = [...content.keys()].sort()
    for (const name of ordered) {
      const buf = content.get(name)
      if (buf) archive.append(buf, { name })
    }

    void archive.finalize()
  })
}

export { GST_PORTAL_URL }
